### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by ibx34** [ibx34/triage-bot#13]
- [ ] Issue claiming
- [ ] Custom config
- [ ] Custom prefix configuration
- [ ] Label management 
- [ ] Milestone, and project management
- [ ] Ability to lock and unlock issues with added features with the bot
- [ ] Pull request management

# Todo
- [ ] Check authorization header on webhooks
